### ISSUE TITLE
A Python code for merging 2 PDF files 

### ISSUE THREAD

**Issue by V-M-Tejus** [V-M-Tejus/Py-Codes#2]

**Comment by SWAYAMKHANDURI** [comment]
Hey there can I work on the issue

**Comment by V-M-Tejus** [comment]
@SWAYAMKHANDURI Can you mail me at vmtejusksit@gmail.com

I want to discuss about a tech issue and then i shall allot you this issue

**Comment by V-M-Tejus** [comment]
@SWAYAMKHANDURI issued to you .

**Comment by abuharish02** [comment]
Can you assign to me ? i want to work on this.

**Comment by V-M-Tejus** [comment]
@abuharish02 

It is already issues to @SWAYAMKHANDURI 

you can try any other issue or else star my repository and contribute to the Hacktoberfest specific 

Smart medication system in py projects section
