### ISSUE TITLE
QR Generation, based on a text input of a prescription(Typed one)

### ISSUE THREAD

**Issue by V-M-Tejus** [V-M-Tejus/Py-Codes#5]
I want a python program which can create a QR for a Given input Typed file which will be a prescription, I want a logo also in middle of the QR, A code is needed to decode it back and fetch data from qr, I will post that as a seperate issue, The person assigned this question only will get accepted for the decoding issue also 

Syntax:

<The basic one line explanation of code>
<Modules to Install>
<The file format input or template defined>
<The Working of each functtion used inside the code><can be inline comments or a seperate paragraph also >
<No personal details to be used in the program, Only arbitrary name and other medicine details have to be given as Sample>

**Comment by vedang999** [comment]
Could you assign this to me please.

**Comment by V-M-Tejus** [comment]
@vedang999 Issued to you

**Comment by V-M-Tejus** [comment]
Guys, I have added the issue to a seperate project altogether, so that contribution becomes easy and based on the response, i will add up more issues to this project so that you all can contribute to all the 4 required contributions for Hacktoberfest 2023 and further also
